### ISSUE TITLE
 Failed setup, will retry: Request failed: Please check the input and try again. (400C04) 

### ISSUE THREAD

**Issue by vonwerderc** [fano0001/home-assistant-mazda#8]
Getting this error when I try to login. I made sure to login to the app with the same username and password, then logout, just to make sure it was working. Not sure if there are any more tweaks I need to get it to work. 

`This error originated from a custom integration.

Logger: custom_components.mazda_cs
Source: custom_components/mazda_cs/__init__.py:159
integration: Mazda Connected Services ng (documentation, issues)
First occurred: 3:38:56 PM (10 occurrences)
Last logged: 3:41:46 PM

Unknown error occurred during Mazda update request: Request failed: Please check the input and try again. (400C04)
Traceback (most recent call last):
  File "/config/custom_components/mazda_cs/__init__.py", line 159, in async_update_data
    vehicle["status"] = await with_timeout(
                        ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda_cs/__init__.py", line 57, in with_timeout
    return await task
           ^^^^^^^^^^
  File "/config/custom_components/mazda_cs/pymazda/client.py", line 97, in get_vehicle_status
    vehicle_status_response = await self.controller.get_vehicle_status(vehicle_id)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda_cs/pymazda/controller.py", line 46, in get_vehicle_status
    response = await self.connection.api_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda_cs/pymazda/connection.py", line 222, in api_request
    return await self.__api_request_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda_cs/pymazda/connection.py", line 252, in __api_request_retry
    return await self.__send_api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda_cs/pymazda/connection.py", line 398, in __send_api_request
    raise MazdaException("Request failed: " + response_json["error"])
custom_components.mazda_cs.pymazda.exceptions.MazdaException: Request failed: Please check the input and try again. (400C04)`

**Comment by townsmcp** [comment]
You need to create a new account via the Mazda app.
Once it is all setup on your phone, log out of the HA Mazda app and then back in with your normal Mazda account. Then log in to HA with the HA Mazda app. 
Ultimately you can’t use 1 account on multiple devices at any one time

**Comment by vonwerderc** [comment]
> You need to create a new account via the Mazda app. Once it is all setup on your phone, log out of the HA Mazda app and then back in with your normal Mazda account. Then log in to HA with the HA Mazda app. Ultimately you can’t use 1 account on multiple devices at any one time

I did that. I have 2 mazda accounts. I logged in with #1 on the mazda app to verify the username/password was working. Logged out. Then logged into account #2. Then I used account #1 to login on HA and I'm getting that error. I tried swapping accounts between the mazda app and HA and logging out completely from the mazda app and trying both accounts on HA. Still getting the same error.

**Comment by townsmcp** [comment]
Perfect. When you look at the integration in HA, what version does it say is installed?

**Comment by vonwerderc** [comment]
> Perfect. When you look at the integration in HA, what version does it say is installed? It should be 1.5.0

It says 1.5. 

![image](https://github.com/user-attachments/assets/e4ef2883-dba1-406c-b36c-e59130e3b2bf)

**Comment by PyrusofImpetus** [comment]
Running into the same here. I just downloaded the integration from HACS, which is labelled as 1.6.0. I sign into the Mazda app, then sign out. I hopen HA, add integration, and add the custom integration from HACS. It now says 1.5.0 just as it does in the screenshot provided by @vonwerderc with the same error code.

**Comment by fano0001** [comment]
Is there still a problem with the latest version of the Integration?
